export PATH=/c/Users/Public/D:$PATH
export PATH=/c/Users/Public/D/dm/bin:$PATH
export PATH=/c/Users/Public/D/dmd2/windows/bin:$PATH
#export PATH=/c/D/dmd2/windows/bin:$PATH
#export PATH=`cygpath -u C://D/dmd2/windows/bin`:$PATH
#export PATH=/c/D/dm/bin:$PATH
#export PATH=`cygpath -u C:/D/dm/bin`:$PATH
#export PATH=/c/Program\ Files\ \(x86\)/Xamarin\ Studio/bin:$PATH
#export PATH=/z/@work//nim-0.17.2/bin:$PATH
#export PATH=/c/Users/javacommons/.cargo/bin:$PATH
#export PATH=~/i686-7.1.0-release-posix-dwarf-rt_v5-rev2/bin:$PATH
#export PATH=~/ldc2-1.4.0-win32-msvc/bin:$PATH
